version: "3.8"

services:
  db:
    image: postgres:15
    container_name: LMS-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: lms_db
    ports:
      - "5433:5432" 
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: LMS-backend
    restart: always
    depends_on:
      - db
    ports:
      - "7070:7070" 
    env_file:
      - .env 
    environment:

      DATABASE_URL: postgresql://postgres:12345@db:5432/lms_db

    command: sh -c "npx prisma generate && npx prisma db push && pnpm run start:dev"

volumes:
  db_data:
